//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eric.Morrison.Harmony.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Eric.Morrison.Harmony.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!DOCTYPE score-partwise PUBLIC &quot;-//Recordare//DTD MusicXML 3.0 Partwise//EN&quot; &quot;http://www.musicxml.org/dtds/partwise.dtd&quot;&gt;
        ///&lt;score-partwise&gt;
        ///	&lt;work&gt;
        ///		&lt;work-title&gt;C:\temp\_xml.xml&lt;/work-title&gt;
        ///	&lt;/work&gt;
        ///	&lt;identification&gt;
        ///		&lt;encoding&gt;
        ///			&lt;software&gt;MuseScore 2.1.0&lt;/software&gt;
        ///			&lt;encoding-date&gt;2017-11-21&lt;/encoding-date&gt;
        ///			&lt;supports element=&quot;accidental&quot; type=&quot;yes&quot;/&gt;
        ///			&lt;supports element=&quot;beam&quot; type=&quot;yes&quot;/&gt;
        ///			&lt;supports element=&quot;print&quot; attribute=&quot;new-page&quot; type=&quot;yes&quot; value=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MusicXML_TEMPLATE {
            get {
                return ResourceManager.GetString("MusicXML_TEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!DOCTYPE score-partwise PUBLIC &quot;-//Recordare//DTD MusicXML 3.0 Partwise//EN&quot; &quot;http://www.musicxml.org/dtds/partwise.dtd&quot;&gt;
        ///&lt;score-partwise&gt;
        ///  &lt;work&gt;
        ///    &lt;work-title&gt;XML Templat 02&lt;/work-title&gt;
        ///    &lt;/work&gt;
        ///  &lt;identification&gt;
        ///    &lt;creator type=&quot;composer&quot;&gt;Generated by HarmonyHelper&lt;/creator&gt;
        ///    &lt;encoding&gt;
        ///      &lt;software&gt;MuseScore 2.1.0&lt;/software&gt;
        ///      &lt;encoding-date&gt;2018-04-14&lt;/encoding-date&gt;
        ///      &lt;supports element=&quot;accidental&quot; type=&quot;yes&quot;/&gt;
        ///      &lt;supports element=&quot;be [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MusicXML_TEMPLATE_02 {
            get {
                return ResourceManager.GetString("MusicXML_TEMPLATE_02", resourceCulture);
            }
        }
    }
}
