<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <OutputType>WinExe</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Contracts\**" />
    <EmbeddedResource Remove="Contracts\**" />
    <None Remove="Contracts\**" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Controls\ChordNameControl.cs" />
    <Compile Update="Controls\ChordNamesControl.cs" />
    <Compile Update="Controls\ChordFormulaSelectorControl.cs" />
    <Compile Update="Controls\ChordsControl.cs" />
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
    <Compile Update="Feature Views\HarmonicAnalysisControl.cs" />
    <Compile Update="Controls\NeckControl\NeckControl.cs" />
    <Compile Update="Controls\ComboBoxes\NoteComboBox.cs" />
    <Compile Update="Controls\NeckControl\StringControl.cs" />
    <Compile Update="Controls\NeckControl\StringPositionControl.cs" />
    <Compile Update="Controls\ScaleSelectorControl.cs" />
    <Compile Update="Views\ModalInterchangeView - Copy.cs">
      <SubType>UserControl</SubType>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="RandomValue">
      <Version>1.0.0</Version>
    </PackageReference>
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageReference Include="Microsoft.DotNet.UpgradeAssistant.Extensions.Default.Analyzers" Version="0.4.421302">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Windows.Compatibility" Version="10.0.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Eric.Morrison.Helpers\Eric.Morrison.Helpers.csproj" />
    <ProjectReference Include="..\HarmonyHelper.IoC\HarmonyHelper.IoC.csproj" />
    <ProjectReference Include="..\HarmonyHelperControls.WinForms\HarmonyHelperControls.WinForms.csproj" />
    <ProjectReference Include="..\HarmonyHelper\HarmonyHelper.csproj" />
    <ProjectReference Include="..\HarmonyHelper_DryWetMidi\HarmonyHelper_DryWetMidi.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>
</Project>