// <auto-generated />
using HarmonyHelper.Dal.CodeFirst;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HarmonyHelper.Dal.CodeFirst.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230222221615_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("Eric.Morrison.Harmony.NoteName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AsciiSortValue")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFlatted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsNatural")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSharped")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("NoteNames");
                });
#pragma warning restore 612, 618
        }
    }
}
