// <auto-generated />
using HarmonyHelper.Dal.CodeFirst;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HarmonyHelper.Dal.CodeFirst.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230222230757_03")]
    partial class _03
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("Eric.Morrison.Harmony.Intervals.Interval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IntervalRoleType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SemiTones")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Intervals");
                });

            modelBuilder.Entity("Eric.Morrison.Harmony.NoteName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AsciiSortValue")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFlatted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsNatural")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSharped")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("NoteNames");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AsciiSortValue = 0,
                            IsFlatted = false,
                            IsNatural = true,
                            IsSharped = false,
                            Name = "C",
                            Value = 2
                        },
                        new
                        {
                            Id = 2,
                            AsciiSortValue = 0,
                            IsFlatted = false,
                            IsNatural = false,
                            IsSharped = true,
                            Name = "C♯",
                            Value = 4
                        },
                        new
                        {
                            Id = 3,
                            AsciiSortValue = 1,
                            IsFlatted = true,
                            IsNatural = false,
                            IsSharped = false,
                            Name = "D♭",
                            Value = 4
                        },
                        new
                        {
                            Id = 4,
                            AsciiSortValue = 1,
                            IsFlatted = false,
                            IsNatural = true,
                            IsSharped = false,
                            Name = "D",
                            Value = 8
                        },
                        new
                        {
                            Id = 5,
                            AsciiSortValue = 1,
                            IsFlatted = false,
                            IsNatural = false,
                            IsSharped = true,
                            Name = "D♯",
                            Value = 16
                        },
                        new
                        {
                            Id = 6,
                            AsciiSortValue = 2,
                            IsFlatted = true,
                            IsNatural = false,
                            IsSharped = false,
                            Name = "E♭",
                            Value = 16
                        },
                        new
                        {
                            Id = 7,
                            AsciiSortValue = 2,
                            IsFlatted = false,
                            IsNatural = true,
                            IsSharped = false,
                            Name = "E",
                            Value = 32
                        },
                        new
                        {
                            Id = 8,
                            AsciiSortValue = 3,
                            IsFlatted = true,
                            IsNatural = false,
                            IsSharped = false,
                            Name = "F♭",
                            Value = 32
                        },
                        new
                        {
                            Id = 9,
                            AsciiSortValue = 2,
                            IsFlatted = false,
                            IsNatural = false,
                            IsSharped = true,
                            Name = "E♯",
                            Value = 64
                        },
                        new
                        {
                            Id = 10,
                            AsciiSortValue = 3,
                            IsFlatted = false,
                            IsNatural = true,
                            IsSharped = false,
                            Name = "F",
                            Value = 64
                        },
                        new
                        {
                            Id = 11,
                            AsciiSortValue = 3,
                            IsFlatted = false,
                            IsNatural = false,
                            IsSharped = true,
                            Name = "F♯",
                            Value = 128
                        },
                        new
                        {
                            Id = 12,
                            AsciiSortValue = 4,
                            IsFlatted = true,
                            IsNatural = false,
                            IsSharped = false,
                            Name = "G♭",
                            Value = 128
                        },
                        new
                        {
                            Id = 13,
                            AsciiSortValue = 4,
                            IsFlatted = false,
                            IsNatural = true,
                            IsSharped = false,
                            Name = "G",
                            Value = 256
                        },
                        new
                        {
                            Id = 14,
                            AsciiSortValue = 4,
                            IsFlatted = false,
                            IsNatural = false,
                            IsSharped = true,
                            Name = "G♯",
                            Value = 512
                        },
                        new
                        {
                            Id = 15,
                            AsciiSortValue = 5,
                            IsFlatted = true,
                            IsNatural = false,
                            IsSharped = false,
                            Name = "A♭",
                            Value = 512
                        },
                        new
                        {
                            Id = 16,
                            AsciiSortValue = 5,
                            IsFlatted = false,
                            IsNatural = true,
                            IsSharped = false,
                            Name = "A",
                            Value = 1024
                        },
                        new
                        {
                            Id = 17,
                            AsciiSortValue = 5,
                            IsFlatted = false,
                            IsNatural = false,
                            IsSharped = true,
                            Name = "A♯",
                            Value = 2048
                        },
                        new
                        {
                            Id = 18,
                            AsciiSortValue = 6,
                            IsFlatted = true,
                            IsNatural = false,
                            IsSharped = false,
                            Name = "B♭",
                            Value = 2048
                        },
                        new
                        {
                            Id = 19,
                            AsciiSortValue = 6,
                            IsFlatted = false,
                            IsNatural = true,
                            IsSharped = false,
                            Name = "B",
                            Value = 4096
                        },
                        new
                        {
                            Id = 20,
                            AsciiSortValue = 0,
                            IsFlatted = true,
                            IsNatural = false,
                            IsSharped = false,
                            Name = "C♭",
                            Value = 4096
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
